services:
  database:
    image: "postgres:16.0-alpine3.18"
    container_name: postgres-dev
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-localuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-localpassword}
      POSTGRES_DB: ${POSTGRES_DB:-localdb}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
